// Code generated by wsdl2dart. DO NOT EDIT.

import 'dart:convert';

import 'package:soap_dart/soap_dart.dart';

const soapTargetNamespace =
    "https://soap-service-free.mock.beeceptor.com/CountryInfoService";

final class ArrayOfContinents implements SoapSerializable {
  final List<Continent> tContinent;

  const ArrayOfContinents({this.tContinent = const []});

  factory ArrayOfContinents.fromXml(XmlElement element) => ArrayOfContinents(
    tContinent: element
        .getElementsByLocalName("tContinent")
        .map(Continent.fromXml)
        .toList(),
  );

  @override
  XmlElement toXmlElement({String? name, String? namespace}) {
    final builder = XmlBuilder();
    builder.element(
      name ?? "ArrayOfContinents",
      nest: () {
        if (namespace != null) {
          builder.attribute('xmlns', namespace);
        }
        for (final item in tContinent) {
          _soapWriteElement(builder, "tContinent", item);
        }
      },
    );
    return builder.buildDocument().rootElement;
  }
}

final class ArrayOfCountryNames implements SoapSerializable {
  final List<CountryCodeAndName> tCountryCodeAndName;

  const ArrayOfCountryNames({this.tCountryCodeAndName = const []});

  factory ArrayOfCountryNames.fromXml(XmlElement element) =>
      ArrayOfCountryNames(
        tCountryCodeAndName: element
            .getElementsByLocalName("tCountryCodeAndName")
            .map(CountryCodeAndName.fromXml)
            .toList(),
      );

  @override
  XmlElement toXmlElement({String? name, String? namespace}) {
    final builder = XmlBuilder();
    builder.element(
      name ?? "ArrayOfCountryNames",
      nest: () {
        if (namespace != null) {
          builder.attribute('xmlns', namespace);
        }
        for (final item in tCountryCodeAndName) {
          _soapWriteElement(builder, "tCountryCodeAndName", item);
        }
      },
    );
    return builder.buildDocument().rootElement;
  }
}

final class Continent implements SoapSerializable {
  final String? sCode;
  final String? sName;

  const Continent({this.sCode, this.sName});

  factory Continent.fromXml(XmlElement element) => Continent(
    sCode: _soapReadElement(
      element,
      "sCode",
      (element) => soapElementText(element) ?? '',
    ),
    sName: _soapReadElement(
      element,
      "sName",
      (element) => soapElementText(element) ?? '',
    ),
  );

  @override
  XmlElement toXmlElement({String? name, String? namespace}) {
    final builder = XmlBuilder();
    builder.element(
      name ?? "Continent",
      nest: () {
        if (namespace != null) {
          builder.attribute('xmlns', namespace);
        }
        _soapWriteElement(builder, "sCode", sCode);
        _soapWriteElement(builder, "sName", sName);
      },
    );
    return builder.buildDocument().rootElement;
  }
}

final class CountryCodeAndName implements SoapSerializable {
  final String? sISOCode;
  final String? sName;

  const CountryCodeAndName({this.sISOCode, this.sName});

  factory CountryCodeAndName.fromXml(XmlElement element) => CountryCodeAndName(
    sISOCode: _soapReadElement(
      element,
      "sISOCode",
      (element) => soapElementText(element) ?? '',
    ),
    sName: _soapReadElement(
      element,
      "sName",
      (element) => soapElementText(element) ?? '',
    ),
  );

  @override
  XmlElement toXmlElement({String? name, String? namespace}) {
    final builder = XmlBuilder();
    builder.element(
      name ?? "CountryCodeAndName",
      nest: () {
        if (namespace != null) {
          builder.attribute('xmlns', namespace);
        }
        _soapWriteElement(builder, "sISOCode", sISOCode);
        _soapWriteElement(builder, "sName", sName);
      },
    );
    return builder.buildDocument().rootElement;
  }
}

final class ListOfContinentsByNameResponseType implements SoapSerializable {
  final ArrayOfContinents? listOfContinentsByNameResult;

  const ListOfContinentsByNameResponseType({this.listOfContinentsByNameResult});

  factory ListOfContinentsByNameResponseType.fromXml(XmlElement element) =>
      ListOfContinentsByNameResponseType(
        listOfContinentsByNameResult: _soapReadElement(
          element,
          "ListOfContinentsByNameResult",
          ArrayOfContinents.fromXml,
        ),
      );

  @override
  XmlElement toXmlElement({String? name, String? namespace}) {
    final builder = XmlBuilder();
    builder.element(
      name ?? "ListOfContinentsByNameResponseType",
      nest: () {
        if (namespace != null) {
          builder.attribute('xmlns', namespace);
        }
        _soapWriteElement(
          builder,
          "ListOfContinentsByNameResult",
          listOfContinentsByNameResult,
        );
      },
    );
    return builder.buildDocument().rootElement;
  }
}

final class ListOfContinentsByNameType implements SoapSerializable {
  const ListOfContinentsByNameType();

  factory ListOfContinentsByNameType.fromXml(XmlElement element) =>
      const ListOfContinentsByNameType();

  @override
  XmlElement toXmlElement({String? name, String? namespace}) {
    final builder = XmlBuilder();
    builder.element(
      name ?? "ListOfContinentsByNameType",
      nest: () {
        if (namespace != null) {
          builder.attribute('xmlns', namespace);
        }
      },
    );
    return builder.buildDocument().rootElement;
  }
}

final class ListOfCountryNamesByNameResponseType implements SoapSerializable {
  final ArrayOfCountryNames? listOfCountryNamesByNameResult;

  const ListOfCountryNamesByNameResponseType({
    this.listOfCountryNamesByNameResult,
  });

  factory ListOfCountryNamesByNameResponseType.fromXml(XmlElement element) =>
      ListOfCountryNamesByNameResponseType(
        listOfCountryNamesByNameResult: _soapReadElement(
          element,
          "ListOfCountryNamesByNameResult",
          ArrayOfCountryNames.fromXml,
        ),
      );

  @override
  XmlElement toXmlElement({String? name, String? namespace}) {
    final builder = XmlBuilder();
    builder.element(
      name ?? "ListOfCountryNamesByNameResponseType",
      nest: () {
        if (namespace != null) {
          builder.attribute('xmlns', namespace);
        }
        _soapWriteElement(
          builder,
          "ListOfCountryNamesByNameResult",
          listOfCountryNamesByNameResult,
        );
      },
    );
    return builder.buildDocument().rootElement;
  }
}

final class ListOfCountryNamesByNameType implements SoapSerializable {
  const ListOfCountryNamesByNameType();

  factory ListOfCountryNamesByNameType.fromXml(XmlElement element) =>
      const ListOfCountryNamesByNameType();

  @override
  XmlElement toXmlElement({String? name, String? namespace}) {
    final builder = XmlBuilder();
    builder.element(
      name ?? "ListOfCountryNamesByNameType",
      nest: () {
        if (namespace != null) {
          builder.attribute('xmlns', namespace);
        }
      },
    );
    return builder.buildDocument().rootElement;
  }
}

final class CountryInfoPortTypeClient {
  final SoapClient _client;

  const CountryInfoPortTypeClient(this._client);

  Future<ListOfContinentsByNameResponseType> listOfContinentsByName(
    ListOfContinentsByNameType request, {
    XmlElement? header,
    Map<String, String> headers = const {},
  }) {
    return _client.call<ListOfContinentsByNameResponseType>(
      body: request.toXmlElement(
        name: "ListOfContinentsByName",
        namespace: soapTargetNamespace,
      ),
      soapAction:
          "https://soap-service-free.mock.beeceptor.com/CountryInfoService.wso/ListOfContinentsByName",
      soap12: false,
      header: header,
      headers: headers,
      decode: ListOfContinentsByNameResponseType.fromXml,
    );
  }

  Future<ListOfCountryNamesByNameResponseType> listOfCountryNamesByName(
    ListOfCountryNamesByNameType request, {
    XmlElement? header,
    Map<String, String> headers = const {},
  }) {
    return _client.call<ListOfCountryNamesByNameResponseType>(
      body: request.toXmlElement(
        name: "ListOfCountryNamesByName",
        namespace: soapTargetNamespace,
      ),
      soapAction:
          "https://soap-service-free.mock.beeceptor.com/CountryInfoService.wso/ListOfCountryNamesByName",
      soap12: false,
      header: header,
      headers: headers,
      decode: ListOfCountryNamesByNameResponseType.fromXml,
    );
  }
}

T? _soapReadElement<T>(
  XmlElement parent,
  String name,
  T Function(XmlElement element) read,
) {
  final child = parent.getElementByLocalName(name);
  return child == null ? null : read(child);
}

void _soapWriteElement(XmlBuilder builder, String name, Object? value) {
  if (value == null) return;
  if (value is SoapSerializable) {
    builder.xml(value.toXmlElement(name: name).toXmlString());
    return;
  }
  if (value is SoapAny) {
    builder.element(
      name,
      nest: () {
        builder.xml(value.toXmlString());
      },
    );
    return;
  }
  builder.element(
    name,
    nest: () {
      builder.text(_soapFormat(value));
    },
  );
}

String _soapFormat(Object value) {
  if (value is DateTime) return value.toUtc().toIso8601String();
  if (value is Duration) return formatXsdDuration(value);
  if (value is bool) return value ? 'true' : 'false';
  if (value is List<int>) return base64Encode(value);
  return value.toString();
}
