import 'dart:convert';

import 'package:code_builder/code_builder.dart' as code;

import '../wsdl/model.dart';
import 'naming.dart';

final class WsdlDartGenerator {
  final String? namespaceOverride;
  final String clientSuffix;

  const WsdlDartGenerator({
    this.namespaceOverride,
    this.clientSuffix = 'Client',
  });

  String generate(WsdlDocument document) {
    final context = _GeneratorContext(document, namespaceOverride);
    return context.generate(clientSuffix: clientSuffix);
  }
}

final class _GeneratorContext {
  final WsdlDocument document;
  final String? namespaceOverride;
  final Map<String, XsdSimpleType> simpleTypes = {};
  final Map<String, XsdComplexType> complexTypes = {};
  final Map<String, XsdElement> elements = {};
  final Map<String, WsdlMessage> messages = {};
  final Map<String, WsdlBinding> bindingsByPortType = {};
  final Map<String, WsdlBindingOperation> bindingOps = {};
  final Set<String> generatedClasses = {};
  final Set<String> generatedMessageClasses = {};
  bool needsEmptySoapMessage = false;

  _GeneratorContext(this.document, this.namespaceOverride) {
    _cache();
  }

  String get namespace =>
      namespaceOverride ?? document.targetNamespace ?? 'urn:soap-dart';

  String generate({required String clientSuffix}) {
    final specs = <code.Spec>[
      _targetNamespaceField(),
      ..._simpleTypes(),
      ..._complexTypes(),
      ..._messageTypes(),
      ..._clients(clientSuffix),
      ..._helpers(),
    ];

    final library = code.Library((builder) {
      builder
        ..comments.add('Code generated by wsdl2dart. DO NOT EDIT.')
        ..directives.add(code.Directive.import('dart:convert'))
        ..directives
            .add(code.Directive.import('package:soap_dart/soap_dart.dart'))
        ..body.addAll(specs);
    });
    return '${library.accept(code.DartEmitter.scoped())}';
  }

  code.Field _targetNamespaceField() {
    return code.Field((builder) {
      builder
        ..name = 'soapTargetNamespace'
        ..modifier = code.FieldModifier.constant
        ..assignment = code.Code(_literal(namespace));
    });
  }

  void _cache() {
    for (final simpleType in document.simpleTypes) {
      final name = simpleType.name;
      if (name != null && name.isNotEmpty) {
        simpleTypes[trimNamespace(name)] = simpleType;
      }
    }
    for (final complexType in document.complexTypes) {
      final name = complexType.name;
      if (name != null && name.isNotEmpty) {
        complexTypes[trimNamespace(name)] = complexType;
      }
    }
    for (final element in document.elements) {
      final name = _elementName(element);
      if (name == null || name.isEmpty) {
        continue;
      }
      elements[trimNamespace(name)] = element;
      if (element.complexType != null) {
        complexTypes.putIfAbsent(
          trimNamespace(name),
          () => _namedComplexType(element.complexType!, name),
        );
      }
    }
    for (final message in document.messages) {
      messages[trimNamespace(message.name)] = message;
    }
    for (final binding in document.bindings) {
      final portType = trimNamespaceOrNull(binding.type);
      if (portType != null && portType.isNotEmpty) {
        bindingsByPortType[portType] = binding;
      }
      for (final op in binding.operations) {
        bindingOps[op.name] = op;
      }
    }
  }

  XsdComplexType _namedComplexType(XsdComplexType type, String name) =>
      XsdComplexType(
        name: name,
        abstract: type.abstract,
        documentation: type.documentation,
        sequence: type.sequence,
        choice: type.choice,
        allElements: type.allElements,
        complexContent: type.complexContent,
        simpleContent: type.simpleContent,
        attributes: type.attributes,
        targetNamespace: type.targetNamespace,
      );

  List<code.Spec> _simpleTypes() {
    final specs = <code.Spec>[];
    final names = simpleTypes.keys.toList()..sort();
    for (final name in names) {
      final simpleType = simpleTypes[name]!;
      final className = dartClassName(name);
      final base = simpleType.restriction?.base;
      final dartType = _dartType(base ?? 'string');
      specs.add(
        code.TypeDef((builder) {
          builder
            ..name = className
            ..definition = _ref(dartType);
        }),
      );
      final values = simpleType.restriction?.enumerations ?? const <String>[];
      if (values.isNotEmpty) {
        specs.add(_simpleTypeValuesClass(className, values));
      }
    }
    return specs;
  }

  code.Class _simpleTypeValuesClass(String className, List<String> values) {
    return code.Class((builder) {
      builder
        ..name = '${className}Values'
        ..abstract = true
        ..modifier = code.ClassModifier.final$;
      for (final value in values) {
        builder.fields.add(
          code.Field((field) {
            field
              ..name = enumConstantName(value)
              ..type = _ref(className)
              ..static = true
              ..modifier = code.FieldModifier.constant
              ..assignment = code.Code(_literal(value));
          }),
        );
      }
    });
  }

  List<code.Spec> _complexTypes() {
    final specs = <code.Spec>[];
    final names = complexTypes.keys.toList()..sort();
    for (final name in names) {
      final type = complexTypes[name]!;
      final classSpec = _classSpec(dartClassName(name), name, _fieldsFor(type));
      if (classSpec != null) {
        specs.add(classSpec);
      }
    }
    return specs;
  }

  List<code.Spec> _messageTypes() {
    final specs = <code.Spec>[];
    for (final portType in document.portTypes) {
      for (final operation in portType.operations) {
        final input = _operationMessage(operation.input);
        if (input != null && _messageElement(input) == null) {
          final classSpec = _messageClass(
            operation,
            input,
            isResponse: false,
          );
          if (classSpec != null) {
            specs.add(classSpec);
          }
        }
        final output = _operationMessage(operation.output);
        if (output != null && _messageElement(output) == null) {
          final classSpec = _messageClass(
            operation,
            output,
            isResponse: true,
          );
          if (classSpec != null) {
            specs.add(classSpec);
          }
        }
      }
    }
    return specs;
  }

  code.Class? _messageClass(
    WsdlOperation operation,
    WsdlMessage message, {
    required bool isResponse,
  }) {
    final className = _operationWrapperClass(operation, isResponse: isResponse);
    if (!generatedMessageClasses.add(className)) {
      return null;
    }
    final fields = message.parts.map((part) {
      final xmlName =
          part.name ?? trimNamespace(part.element ?? part.type ?? 'value');
      final type = _partDartType(part);
      return _Field(
        xmlName: xmlName,
        dartName: dartFieldName(xmlName),
        type: type,
        list: false,
        attribute: false,
        nullable: true,
        custom: _isCustomType(type),
      );
    }).toList();
    return _classSpec(
      className,
      operation.name,
      fields,
      forcedElementName:
          isResponse ? '${operation.name}Response' : operation.name,
    );
  }

  List<code.Spec> _clients(String clientSuffix) {
    final specs = <code.Spec>[];
    for (final portType in document.portTypes) {
      final className = '${dartClassName(portType.name)}$clientSuffix';
      final binding = bindingsByPortType[portType.name];
      specs.add(
        code.Class((builder) {
          builder
            ..name = className
            ..modifier = code.ClassModifier.final$
            ..constructors.add(
              code.Constructor((constructor) {
                constructor
                  ..constant = true
                  ..requiredParameters.add(
                    _parameter('_client', toThis: true),
                  );
              }),
            )
            ..fields.add(
              code.Field((field) {
                field
                  ..name = '_client'
                  ..type = _ref('SoapClient')
                  ..modifier = code.FieldModifier.final$;
              }),
            );
          for (final operation in portType.operations) {
            builder.methods.add(_operation(operation, binding));
          }
        }),
      );
    }
    return specs;
  }

  code.Method _operation(
    WsdlOperation operation,
    WsdlBinding? binding,
  ) {
    final inputMessage = _operationMessage(operation.input);
    final outputMessage = _operationMessage(operation.output);
    final inputElement =
        inputMessage == null ? null : _messageElement(inputMessage);
    final outputElement =
        outputMessage == null ? null : _messageElement(outputMessage);
    final requestType = inputMessage == null
        ? null
        : inputElement == null
            ? _operationWrapperClass(operation, isResponse: false)
            : _elementDartType(inputElement);
    final responseType = outputMessage == null
        ? 'XmlElement'
        : outputElement == null
            ? _operationWrapperClass(operation, isResponse: true)
            : _elementDartType(outputElement);
    final methodName = dartMethodName(operation.name);
    final bindingOp = binding?.operations
            .where((item) => item.name == operation.name)
            .firstOrNull ??
        bindingOps[operation.name];
    final soapAction = bindingOp?.soapAction;
    final soap12 = bindingOp?.soap12 ?? false;
    final bodyName = inputElement == null
        ? operation.name
        : _elementName(inputElement) ?? operation.name;
    final responseReader = responseType == 'XmlElement'
        ? '(element) => element'
        : '$responseType.fromXml';

    if (requestType == null) {
      needsEmptySoapMessage = true;
      return code.Method((builder) {
        builder
          ..name = methodName
          ..returns = _ref('Future<$responseType>')
          ..optionalParameters.addAll(_callOptionsParameters())
          ..body = code.Code('''
final request = _EmptySoapMessage(${_literal(bodyName)});
return _client.call<$responseType>(
  body: request.toXmlElement(namespace: soapTargetNamespace),
  soapAction: ${_literalOrNull(soapAction)},
  soap12: $soap12,
  header: header,
  headers: headers,
  decode: $responseReader,
);
''');
      });
    }

    return code.Method((builder) {
      builder
        ..name = methodName
        ..returns = _ref('Future<$responseType>')
        ..requiredParameters.add(
          _parameter('request', type: requestType),
        )
        ..optionalParameters.addAll(_callOptionsParameters())
        ..body = code.Code('''
return _client.call<$responseType>(
  body: request.toXmlElement(name: ${_literal(bodyName)}, namespace: soapTargetNamespace),
  soapAction: ${_literalOrNull(soapAction)},
  soap12: $soap12,
  header: header,
  headers: headers,
  decode: $responseReader,
);
''');
    });
  }

  List<code.Parameter> _callOptionsParameters() => [
        _parameter('header', type: 'XmlElement?', named: true),
        _parameter(
          'headers',
          type: 'Map<String, String>',
          named: true,
          defaultTo: 'const {}',
        ),
      ];

  code.Class? _classSpec(
    String className,
    String xmlName,
    List<_Field> fields, {
    String? forcedElementName,
  }) {
    if (!generatedClasses.add(className)) {
      return null;
    }
    final elementName = forcedElementName ?? xmlName;
    return code.Class((builder) {
      builder
        ..name = className
        ..modifier = code.ClassModifier.final$
        ..implements.add(_ref('SoapSerializable'))
        ..constructors.add(_modelConstructor(fields))
        ..constructors.add(_fromXmlConstructor(className, fields))
        ..methods.add(_toXmlElementMethod(elementName, fields));
      for (final field in fields) {
        final type = field.list ? 'List<${field.type}>' : '${field.type}?';
        builder.fields.add(
          code.Field((fieldBuilder) {
            fieldBuilder
              ..name = field.dartName
              ..type = _ref(type)
              ..modifier = code.FieldModifier.final$;
          }),
        );
      }
    });
  }

  code.Constructor _modelConstructor(List<_Field> fields) {
    return code.Constructor((builder) {
      builder.constant = true;
      for (final field in fields) {
        builder.optionalParameters.add(
          _parameter(
            field.dartName,
            named: true,
            toThis: true,
            defaultTo: field.list ? 'const []' : null,
          ),
        );
      }
    });
  }

  code.Constructor _fromXmlConstructor(String className, List<_Field> fields) {
    if (fields.isEmpty) {
      return code.Constructor((builder) {
        builder
          ..name = 'fromXml'
          ..factory = true
          ..lambda = true
          ..requiredParameters.add(_parameter('element', type: 'XmlElement'))
          ..body = code.Code('const $className()');
      });
    }

    final body = [
      '$className(',
      for (final field in fields)
        '  ${field.dartName}: ${_readExpression(field)},',
      ')',
    ].join('\n');
    return code.Constructor((builder) {
      builder
        ..name = 'fromXml'
        ..factory = true
        ..lambda = true
        ..requiredParameters.add(_parameter('element', type: 'XmlElement'))
        ..body = code.Code(body);
    });
  }

  code.Method _toXmlElementMethod(String elementName, List<_Field> fields) {
    final statements = <String>[
      'final builder = XmlBuilder();',
      'builder.element(name ?? ${_literal(elementName)}, nest: () {',
      '  if (namespace != null) {',
      "    builder.attribute('xmlns', namespace);",
      '  }',
    ];
    for (final field in fields.where((field) => field.attribute)) {
      statements.add(
        'if (${field.dartName} != null) builder.attribute(${_literal(field.xmlName)}, _soapFormat(${field.dartName}!));',
      );
    }
    for (final field in fields.where((field) => !field.attribute)) {
      if (field.list) {
        statements.add('''
for (final item in ${field.dartName}) {
  _soapWriteElement(builder, ${_literal(field.xmlName)}, item);
}
''');
      } else {
        statements.add(
          '_soapWriteElement(builder, ${_literal(field.xmlName)}, ${field.dartName});',
        );
      }
    }
    statements
      ..add('});')
      ..add('return builder.buildDocument().rootElement;');

    return code.Method((builder) {
      builder
        ..name = 'toXmlElement'
        ..annotations.add(code.CodeExpression(code.Code('override')))
        ..returns = _ref('XmlElement')
        ..optionalParameters.addAll([
          _parameter('name', type: 'String?', named: true),
          _parameter('namespace', type: 'String?', named: true),
        ])
        ..body = code.Code(statements.join('\n'));
    });
  }

  String _readExpression(_Field field) {
    if (field.attribute) {
      return _readScalarExpression(
        field.type,
        'element.getAttribute(${_literal(field.xmlName)})',
      );
    }
    if (field.list) {
      final reader = _readerForType(field.type);
      return 'element.getElementsByLocalName(${_literal(field.xmlName)})'
          '.map($reader).toList()';
    }
    final reader = _readerForType(field.type);
    return "_soapReadElement(element, ${_literal(field.xmlName)}, $reader)";
  }

  String _readerForType(String type) {
    final simpleBase = _simpleAliasBase(type);
    if (simpleBase != null) {
      return _readerForType(simpleBase);
    }
    switch (type) {
      case 'String':
        return '(element) => soapElementText(element) ?? \'\'';
      case 'int':
        return '(element) => soapParseInt(soapElementText(element)) ?? 0';
      case 'double':
        return '(element) => soapParseDouble(soapElementText(element)) ?? 0';
      case 'bool':
        return '(element) => soapParseBool(soapElementText(element)) ?? false';
      case 'DateTime':
        return '(element) => soapParseDateTime(soapElementText(element)) ?? DateTime.fromMillisecondsSinceEpoch(0, isUtc: true)';
      case 'Duration':
        return '(element) => soapParseDuration(soapElementText(element)) ?? Duration.zero';
      case 'List<int>':
        return '(element) => base64Decode(soapElementText(element) ?? \'\')';
      case 'SoapAny':
        return 'SoapAny.fromElement';
      default:
        return '$type.fromXml';
    }
  }

  String _readScalarExpression(String type, String source) {
    final simpleBase = _simpleAliasBase(type);
    if (simpleBase != null) {
      return _readScalarExpression(simpleBase, source);
    }
    switch (type) {
      case 'String':
        return source;
      case 'int':
        return 'soapParseInt($source)';
      case 'double':
        return 'soapParseDouble($source)';
      case 'bool':
        return 'soapParseBool($source)';
      case 'DateTime':
        return 'soapParseDateTime($source)';
      case 'Duration':
        return 'soapParseDuration($source)';
      default:
        return source;
    }
  }

  List<code.Spec> _helpers() {
    final specs = <code.Spec>[
      if (needsEmptySoapMessage) _emptySoapMessageClass(),
      _readElementHelper(),
      _writeElementHelper(),
      _formatHelper(),
    ];
    return specs;
  }

  code.Class _emptySoapMessageClass() {
    return code.Class((builder) {
      builder
        ..name = '_EmptySoapMessage'
        ..modifier = code.ClassModifier.final$
        ..implements.add(_ref('SoapSerializable'))
        ..constructors.add(
          code.Constructor((constructor) {
            constructor
              ..constant = true
              ..requiredParameters.add(_parameter('elementName', toThis: true));
          }),
        )
        ..fields.add(
          code.Field((field) {
            field
              ..name = 'elementName'
              ..type = _ref('String')
              ..modifier = code.FieldModifier.final$;
          }),
        )
        ..methods.add(
          code.Method((method) {
            method
              ..name = 'toXmlElement'
              ..annotations.add(code.CodeExpression(code.Code('override')))
              ..returns = _ref('XmlElement')
              ..optionalParameters.addAll([
                _parameter('name', type: 'String?', named: true),
                _parameter('namespace', type: 'String?', named: true),
              ])
              ..body = code.Code(r'''
final builder = XmlBuilder();
builder.element(name ?? elementName, nest: () {
  if (namespace != null) {
    builder.attribute('xmlns', namespace);
  }
});
return builder.buildDocument().rootElement;
''');
          }),
        );
    });
  }

  code.Method _readElementHelper() {
    return code.Method((builder) {
      builder
        ..name = '_soapReadElement'
        ..types.add(_ref('T'))
        ..returns = _ref('T?')
        ..requiredParameters.addAll([
          _parameter('parent', type: 'XmlElement'),
          _parameter('name', type: 'String'),
          _parameter('read', type: 'T Function(XmlElement element)'),
        ])
        ..body = code.Code('''
final child = parent.getElementByLocalName(name);
return child == null ? null : read(child);
''');
    });
  }

  code.Method _writeElementHelper() {
    return code.Method.returnsVoid((builder) {
      builder
        ..name = '_soapWriteElement'
        ..requiredParameters.addAll([
          _parameter('builder', type: 'XmlBuilder'),
          _parameter('name', type: 'String'),
          _parameter('value', type: 'Object?'),
        ])
        ..body = code.Code(r'''
if (value == null) return;
if (value is SoapSerializable) {
  builder.xml(value.toXmlElement(name: name).toXmlString());
  return;
}
if (value is SoapAny) {
  builder.element(name, nest: () {
    builder.xml(value.toXmlString());
  });
  return;
}
builder.element(name, nest: () {
  builder.text(_soapFormat(value));
});
''');
    });
  }

  code.Method _formatHelper() {
    return code.Method((builder) {
      builder
        ..name = '_soapFormat'
        ..returns = _ref('String')
        ..requiredParameters.add(_parameter('value', type: 'Object'))
        ..body = code.Code(r'''
if (value is DateTime) return value.toUtc().toIso8601String();
if (value is Duration) return formatXsdDuration(value);
if (value is bool) return value ? 'true' : 'false';
if (value is List<int>) return base64Encode(value);
return value.toString();
''');
    });
  }

  List<_Field> _fieldsFor(XsdComplexType type) {
    final fields = <_Field>[];

    final simpleExtension = type.simpleContent?.extension;
    if (simpleExtension != null) {
      fields.add(
        _Field(
          xmlName: 'value',
          dartName: 'value',
          type: _dartType(simpleExtension.base ?? 'string'),
          list: false,
          attribute: false,
          nullable: true,
          custom: false,
        ),
      );
      fields.addAll(simpleExtension.attributes.map(_fieldForAttribute));
    }

    final complexExtension = type.complexContent?.extension;
    if (complexExtension != null) {
      final baseName = trimNamespaceOrNull(complexExtension.base);
      final baseType = baseName == null ? null : complexTypes[baseName];
      if (baseType != null && !identical(baseType, type)) {
        fields.addAll(_fieldsFor(baseType));
      }
      fields.addAll(_fieldsForSequence(complexExtension.sequence));
      fields.addAll(_fieldsForChoice(complexExtension.choice));
      fields.addAll(complexExtension.attributes.map(_fieldForAttribute));
    }

    fields
      ..addAll(type.allElements.map(_fieldForElement))
      ..addAll(_fieldsForSequence(type.sequence))
      ..addAll(_fieldsForChoice(type.choice))
      ..addAll(type.attributes.map(_fieldForAttribute));

    return _deduplicateFields(fields);
  }

  List<_Field> _fieldsForSequence(XsdSequence? sequence) {
    if (sequence == null) {
      return const [];
    }
    return [
      ...sequence.elements.map(_fieldForElement),
      for (var i = 0; i < sequence.any.length; i++)
        _Field(
          xmlName: 'any',
          dartName: i == 0 ? 'any' : 'any$i',
          type: 'SoapAny',
          list: sequence.any[i].maxOccurs == 'unbounded',
          attribute: false,
          nullable: sequence.any[i].minOccurs == 0,
          custom: false,
        ),
      ...sequence.choices.expand(_fieldsForChoice),
    ];
  }

  List<_Field> _fieldsForChoice(XsdChoice? choice) {
    if (choice == null) {
      return const [];
    }
    return [
      ...choice.elements.map(_fieldForElement),
      for (var i = 0; i < choice.any.length; i++)
        _Field(
          xmlName: 'any',
          dartName: i == 0 ? 'any' : 'any$i',
          type: 'SoapAny',
          list: choice.any[i].maxOccurs == 'unbounded',
          attribute: false,
          nullable: choice.any[i].minOccurs == 0,
          custom: false,
        ),
    ];
  }

  _Field _fieldForElement(XsdElement element) {
    final xmlName = _elementName(element) ?? 'value';
    final type = _elementDartType(element);
    return _Field(
      xmlName: trimNamespace(xmlName),
      dartName: dartFieldName(xmlName),
      type: type,
      list: element.isMany,
      attribute: false,
      nullable: element.minOccurs == 0 || element.nillable,
      custom: _isCustomType(type),
    );
  }

  _Field _fieldForAttribute(XsdAttribute attribute) {
    final xmlName = attribute.name ?? attribute.ref ?? 'value';
    final type = _dartType(attribute.type ?? attribute.arrayType ?? 'string');
    return _Field(
      xmlName: trimNamespace(xmlName),
      dartName: dartFieldName(xmlName),
      type: type,
      list: false,
      attribute: true,
      nullable: attribute.use != 'required',
      custom: _isCustomType(type),
    );
  }

  List<_Field> _deduplicateFields(List<_Field> fields) {
    final seen = <String, int>{};
    return fields.map((field) {
      final count = seen.update(
        field.dartName,
        (value) => value + 1,
        ifAbsent: () => 0,
      );
      if (count == 0) {
        return field;
      }
      return field.copyWith(dartName: '${field.dartName}$count');
    }).toList();
  }

  WsdlMessage? _operationMessage(WsdlOperationIo? io) {
    final messageName = trimNamespaceOrNull(io?.message);
    if (messageName == null) {
      return null;
    }
    return messages[messageName];
  }

  XsdElement? _messageElement(WsdlMessage message) {
    if (message.parts.length != 1) {
      return null;
    }
    final elementName = trimNamespaceOrNull(message.parts.single.element);
    if (elementName == null) {
      return null;
    }
    return elements[elementName];
  }

  String _operationWrapperClass(
    WsdlOperation operation, {
    required bool isResponse,
  }) =>
      'Operation${dartClassName(operation.name)}${isResponse ? 'Response' : 'Request'}';

  String _partDartType(WsdlPart part) {
    final elementName = trimNamespaceOrNull(part.element);
    if (elementName != null) {
      final element = elements[elementName];
      if (element != null) {
        return _elementDartType(element);
      }
    }
    return _dartType(part.type ?? part.element ?? 'string');
  }

  String _elementDartType(XsdElement element) {
    final ref = trimNamespaceOrNull(element.ref);
    if (ref != null && elements.containsKey(ref)) {
      return _elementDartType(elements[ref]!);
    }
    final name = _elementName(element);
    if (element.complexType != null && name != null) {
      return dartClassName(name);
    }
    if (element.simpleType?.restriction?.base != null) {
      return _dartType(element.simpleType!.restriction!.base!);
    }
    return _dartType(element.type ?? name ?? 'string');
  }

  String _dartType(String wsdlType) {
    final local = trimNamespace(wsdlType).toLowerCase();
    final original = trimNamespace(wsdlType);
    if (simpleTypes.containsKey(original)) {
      return dartClassName(original);
    }
    if (complexTypes.containsKey(original) || elements.containsKey(original)) {
      return dartClassName(original);
    }
    switch (local) {
      case 'string':
      case 'token':
      case 'nmtoken':
      case 'normalizedstring':
      case 'anyuri':
      case 'qname':
      case 'language':
      case 'id':
      case 'time':
        return 'String';
      case 'byte':
      case 'unsignedbyte':
      case 'short':
      case 'unsignedshort':
      case 'int':
      case 'integer':
      case 'long':
      case 'unsignedint':
      case 'unsignedlong':
      case 'nonnegativeinteger':
      case 'positiveinteger':
        return 'int';
      case 'float':
      case 'double':
      case 'decimal':
        return 'double';
      case 'boolean':
        return 'bool';
      case 'date':
      case 'datetime':
        return 'DateTime';
      case 'duration':
        return 'Duration';
      case 'hexbinary':
      case 'base64binary':
        return 'List<int>';
      case 'anysequence':
      case 'anytype':
      case 'anysimpletype':
        return 'SoapAny';
      default:
        return dartClassName(original);
    }
  }

  bool _isCustomType(String type) => !{
        'String',
        'int',
        'double',
        'bool',
        'DateTime',
        'Duration',
        'List<int>',
        'SoapAny',
      }.contains(type);

  String? _elementName(XsdElement element) => element.name ?? element.ref;

  String? _simpleAliasBase(String type) {
    for (final entry in simpleTypes.entries) {
      if (dartClassName(entry.key) != type) {
        continue;
      }
      final base = entry.value.restriction?.base;
      return base == null ? 'String' : _dartType(base);
    }
    return null;
  }
}

final class _Field {
  final String xmlName;
  final String dartName;
  final String type;
  final bool list;
  final bool attribute;
  final bool nullable;
  final bool custom;

  const _Field({
    required this.xmlName,
    required this.dartName,
    required this.type,
    required this.list,
    required this.attribute,
    required this.nullable,
    required this.custom,
  });

  _Field copyWith({String? dartName}) => _Field(
        xmlName: xmlName,
        dartName: dartName ?? this.dartName,
        type: type,
        list: list,
        attribute: attribute,
        nullable: nullable,
        custom: custom,
      );
}

code.Reference _ref(String symbol) => code.refer(symbol);

code.Parameter _parameter(
  String name, {
  String? type,
  bool named = false,
  bool toThis = false,
  String? defaultTo,
}) {
  return code.Parameter((builder) {
    builder
      ..name = name
      ..named = named
      ..toThis = toThis;
    if (type != null) {
      builder.type = _ref(type);
    }
    if (defaultTo != null) {
      builder.defaultTo = code.Code(defaultTo);
    }
  });
}

String _literal(String value) => jsonEncode(value);

String _literalOrNull(String? value) =>
    value == null ? 'null' : _literal(value);

extension _FirstOrNull<T> on Iterable<T> {
  T? get firstOrNull {
    final iterator = this.iterator;
    if (!iterator.moveNext()) {
      return null;
    }
    return iterator.current;
  }
}
